"""SPICE Netlist Exporter (ngspice dialect).

Converts a loaded crossbar model into a SPICE netlist for
circuit-level simulation and validation with ngspice or LTspice.

Netlist structure generated
---------------------------
  * One subcircuit per crossbar tile: ``.subckt xbar_<name> ...``
  * Each cell is a resistor R_{i}_{j} with value = 1/G_ij (Ohms)
  * Row drivers: voltage sources V_row_i on word lines
  * Column loads: sense resistors R_load_j on bit lines (1 kΩ default)
  * Top-level analysis: ``.dc`` sweep + ``.print`` statement

Usage::

    from analoglib.exporters.spice import SpiceExporter
    exporter = SpiceExporter(dialect="ngspice")
    exporter.export("circuit.cir", crossbars)
"""

from __future__ import annotations

import textwrap
from pathlib import Path
from typing import Any, List, Optional

import numpy as np

from ..crossbar.crossbar import Crossbar


class SpiceExporter:
    """Export crossbar arrays to SPICE netlists.

    Parameters
    ----------
    dialect : str
        Target SPICE dialect: ``"ngspice"`` (default) or ``"ltspice"``.
    R_load : float
        Sense (load) resistance on each output column in Ohms (default 1 kΩ).
    V_dd : float
        Supply voltage for row drivers (Volts, default 1.0 V).
    include_comments : bool
        Include human-readable comments in the netlist.
    """

    _SUPPORTED = ("ngspice", "ltspice")

    def __init__(
        self,
        dialect: str = "ngspice",
        R_load: float = 1e3,
        V_dd: float = 1.0,
        include_comments: bool = True,
    ) -> None:
        if dialect not in self._SUPPORTED:
            raise ValueError(f"dialect must be one of {self._SUPPORTED}, got {dialect!r}")
        self.dialect         = dialect
        self.R_load          = R_load
        self.V_dd            = V_dd
        self.include_comments = include_comments

    def export(
        self,
        path: str | Path,
        crossbars: List[Crossbar],
        *,
        title: str = "AnalogLib Crossbar Export",
        V_inputs: Optional[np.ndarray] = None,
    ) -> Path:
        """Generate SPICE netlist from crossbar layers.

        Parameters
        ----------
        path : str or Path
            Output file path. ``.cir`` extension added if missing.
        crossbars : list of Crossbar
            Loaded crossbar arrays to export.
        title : str
            Netlist title comment.
        V_inputs : ndarray, optional
            Input voltage vector. If provided, includes ``.dc`` analysis.

        Returns
        -------
        Path
            Absolute path to the generated netlist file.
        """
        path = Path(path)
        if path.suffix == "":
            path = path.with_suffix(".cir")
        path.parent.mkdir(parents=True, exist_ok=True)

        lines = self._gen_netlist(crossbars, title=title, V_inputs=V_inputs)
        path.write_text("\n".join(lines), encoding="ascii")
        return path.resolve()

    def export_str(
        self,
        crossbars: List[Crossbar],
        title: str = "AnalogLib Export",
    ) -> str:
        """Return the netlist as a string (for testing/inspection)."""
        return "\n".join(self._gen_netlist(crossbars, title=title))

    # ------------------------------------------------------------------
    # Generation
    # ------------------------------------------------------------------

    def _gen_netlist(
        self,
        crossbars: List[Crossbar],
        title: str,
        V_inputs: Optional[np.ndarray] = None,
    ) -> List[str]:
        out: List[str] = []
        c = self._comment

        out += [f"* {title}"]
        out += [c(f"Generated by AnalogLib SpiceExporter (dialect={self.dialect})")]
        out += [c("=" * 60), ""]

        # Include library if ngspice
        if self.dialect == "ngspice":
            out += [".options warn=1", ""]

        # Subcircuit for each crossbar layer
        for i, xbar in enumerate(crossbars):
            out += self._gen_subcircuit(xbar, i)
            out += [""]

        # Top-level instantiation
        out += [c("=== Top-Level Instantiation ===")]
        node_in  = "n_in"
        node_out = "n_out"

        for i, xbar in enumerate(crossbars):
            rows, cols = xbar.rows, xbar.cols
            row_nodes = " ".join(f"{node_in}_{i}_{r}" for r in range(rows))
            col_nodes = " ".join(f"{node_out}_{i}_{c2}" for c2 in range(cols))
            out += [f"X_xbar{i} {row_nodes} {col_nodes} GND xbar_{i}"]

        # Row driver voltage sources
        if V_inputs is not None and len(crossbars) > 0:
            V_in = np.asarray(V_inputs).ravel()
            n_rows = crossbars[0].rows
            for r in range(min(n_rows, len(V_in))):
                v = float(V_in[r])
                out += [f"V_row_{r} n_in_0_{r} GND DC {v:.6f}"]
        else:
            # Default: all row drivers at V_dd
            if crossbars:
                for r in range(crossbars[0].rows):
                    out += [f"V_row_{r} n_in_0_{r} GND DC {self.V_dd:.3f}"]

        out += [""]

        # Analysis commands
        if self.dialect == "ngspice":
            out += [".op"]
            if crossbars:
                last = len(crossbars) - 1
                for c2 in range(crossbars[-1].cols):
                    out += [f".print op V(n_out_{last}_{c2})"]
            out += [".end"]
        else:
            out += [".op", ".backanno", ".end"]

        return out

    def _gen_subcircuit(self, xbar: Crossbar, idx: int) -> List[str]:
        """Generate subcircuit for one crossbar layer."""
        rows, cols = xbar.rows, xbar.cols
        G_pos, G_neg = xbar.get_conductance()
        G_eff = G_pos - G_neg  # effective conductance

        row_ports = " ".join(f"row_{r}" for r in range(rows))
        col_ports = " ".join(f"col_{c}" for c in range(cols))
        lines = [
            f"* Crossbar layer {idx}: {rows}x{cols}",
            f".subckt xbar_{idx} {row_ports} {col_ports} GND",
        ]

        if self.include_comments:
            lines += [f"* G_min={xbar.device.g_min:.2e} G_max={xbar.device.g_max:.2e}"]

        # Cell resistors: R_{i}_{j} with resistance = 1/|G_eff|
        for i in range(rows):
            for j in range(cols):
                g = abs(G_eff[i, j])
                if g < 1e-15:
                    r_val = 1e15  # open circuit for zero conductance
                else:
                    r_val = 1.0 / g
                # Positive arm (G+ physics)
                g_pos = G_pos[i, j]
                r_pos = 1.0 / max(g_pos, 1e-15)
                # Negative arm (G-)
                g_neg = G_neg[i, j] if G_neg is not None else 0.0
                r_neg = 1.0 / max(g_neg, 1e-15)

                lines += [
                    f"R_pos_{i}_{j} row_{i} col_{j} {r_pos:.6e}  $ G+={G_pos[i,j]:.3e}",
                ]
                if xbar.differential:
                    lines += [
                        f"R_neg_{i}_{j} row_{i} n_neg_{i}_{j} {r_neg:.6e}  $ G-={g_neg:.3e}",
                        f"I_diff_{i}_{j} n_neg_{i}_{j} col_{j} DC 0",
                    ]

        # Column load resistors
        for j in range(cols):
            lines += [f"R_load_{j} col_{j} GND {self.R_load:.3e}"]

        lines += [".ends"]
        return lines

    def _comment(self, text: str) -> str:
        return f"* {text}"
